version: "3.9"

services:
  kafka:
    image: bitnami/kafka:3.3.2
    hostname: kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL1://:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL1:PLAINTEXT,EXTERNAL2:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092,EXTERNAL1://kafka:9094
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - BITNAMI_DEBUG=yes
      - KAFKA_CFG_NUM_PARTITIONS=2
    networks:
      - malware-scanner

  kafka-ui:
    container_name: kafka-ui
    depends_on:
      - kafka
    image: provectuslabs/kafka-ui:latest
    ports:
      - "18080:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      LOGGING_LEVEL_ROOT: 'INFO'
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'kafka:9094'
    networks:
      - malware-scanner

  malware-scanner:
    image: ogami/malware-scanner:latest
    container_name: malware-scanner
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      spring.kafka.bootstrap-servers: kafka:9094
      spring.kafka.consumer.group-id: malware-scanner
    networks:
      - malware-scanner

networks:
  malware-scanner:
